### ISSUE TITLE
low benchmark scores

### ISSUE THREAD

**Issue by programmerjake** [mamcx/tree-flat#1]
from looking at your benchmark scores, they seem really low (by a factor of 10-100x) for reading/writing contiguous memory, even if your doing some other stuff too...did you remember to benchmark with optimizations enabled? you never mentioned the commands you used in the blog entry so I couldn't tell.

**Comment by mamcx** [comment]
I don't do anything special, according to my understanding of bench/criterion it already runs with optimizations enabled?

**Comment by programmerjake** [comment]
hmm... maybe allocator stuff? i would have tested with much bigger trees, from reading your code, the trees appear to only have 10-20 elements, so the vast majority of the time would be allocating/freeing the arena/vec's memory. anyway, i'll close this issue since it does appear as though optimizations are enabled.
