### ISSUE TITLE
Generalize to accept given collection types?

### ISSUE THREAD

**Issue by taqtiqa-mark** [mamcx/tree-flat#2]
Thanks you for making this available.
Would it make sense be possible to generalize this to allow some other collection? Say some newtype specialization of Vec or Hash*

**Comment by mamcx** [comment]
I don't understand this. This crate *is* a collection.

**Comment by taqtiqa-mark** [comment]
Apologies for the ambiguity - I am still wrapping my head around arenas, how (best) to use them and whether they might suit a use case I have in mind.

What I was referring to is, I believe, here:

https://github.com/mamcx/tree-flat/blob/6da1e91f6ff30d407a308faf330ce672ffe8018f/src/tree.rs#L14-L16

IIUC, it makes no sense to use anything other then `Vec` for the level and parent - correct?
My question is more around the `data` .  I'm wondering what happens when a user has some other collection they use to hold data, say trait objects.  Or perhaps they use a `Vec`-newtype - one of the uses of a newtype pattern is to hide some functionality of the underlying type... which raises the question about what functions/methods would a user "defined" type be required to provide, etc.

Hopefully that is clearer - apologies for any remaining ambiguity.

**Comment by mamcx** [comment]
The use of generics means here it can store anything. The collection only says what operations apply to _itself_, not what the items can do.

P.D: If wanna answer for know more about arenas instead of this crate, go to https://www.reddit.com/r/rust/, so you can get more useful answers!

**Comment by taqtiqa-mark** [comment]
> The use of generics means here it can store anything.

\<blush\>Thanks - over thinking this :) \</blush\>
