### ISSUE TITLE
Children and Siblings are wrong

### ISSUE THREAD

**Issue by Timmmm** [mamcx/tree-flat#5]
This may be a language issue, but the children and siblings iterators do not do what they say. In the example from the tests:

```
// . 0
// ├── 1
// ├   ├── 2
// ├── 3
// ├   ├── 4
// ├   ├   ├── 5
// ├   ├── 6
// ├── 7
// ├   ├── 8
// ├   ├   ├── 9
// ├   ├   ├── 10
// ├   ├── 11
// ├   ├   ├── 12
// ├   ├   ├── 13
// └────── 14
```

The children of 0 are 1, 3 and 7. The other nodes are *descendants*. I would rename `children` to `descendants`.

Similarly, the siblings of 12 are 13 and 14. 9 and 10 are not siblings of 12. I'm not sure why you would ever want the `get_all_nodes_at_same_level` operation really but I would rename it to something other than `siblings` (or maybe just remove it).

Don't worry too much about fixing these. I decided to write my own version of this library. Yours was a great inspiration though, thanks!

**Comment by Timmmm** [comment]
> I decided to write my own version of this library.

[Et voila.](https://crates.io/crates/espalier)

Thanks again for making your library. Would have taken me longer to do mine without yours as a reference. 👍

**Comment by mamcx** [comment]
Good luck with your library. Is nice to see an idea spread!
