### ISSUE TITLE
Does it support remove or detach node?

### ISSUE THREAD

**Issue by saona-raimundo** [mamcx/tree-flat#6]
Thanks for the crate!

Is removing a node a planned feature?

I saw the [discussion in ego-tree](causal-agent/ego-tree#11). 
They decided to detach but not remove the node to not change the underlying structure.

**Comment by mamcx** [comment]
That is something I wish to do, have not decided precisely how. Probably with a sentinel value or a bitmap.

In short, the tree can't be mutated at all except build (insert).

**Comment by saona-raimundo** [comment]
Thanks for the answer!

Just for curiosity, `pop` operations should be easy, no? 
Somehow, this is the simplest removal.

**Comment by mamcx** [comment]
Yeah, because all of this is on `Vec` `insert/pop` is the easiest/fastest ops.

`update` of the data payload is also easy, because not change the tree. Is moving around the `parent/child` relation that is tricky.

**Comment by saona-raimundo** [comment]
Sounds good :) 

## Implementation approach

Personally, I think that this crate would benefit from having this removal mechanism as a feature (so that one could turn it off). 

For the bitmap approach, there is (almost) no harm, since one is paying the cost only if there is an actual removal operation.
For the sentinel approach, one is paying the cost even if no removal occurs. 

## Exposing more API from Vec

I like that the API is short and simple, but, at the same time, the underlying vectors are not exposed at all. 
I do not know how much you want to expose them, but there are a few methods that have a clear translation
- capacity
- clear
- drain(?) (needs a representation of the nodes, maybe `(T, usize, usize)`)
- pop
- reserve
- reserve_exact
- shrink_to_fit

Other methods require the user to know the order of insertion, just like pop requires to remember the last inserted node. I find pop less error-prone.
- shrink_to
- truncate

## Offering help

Would you like a PR for any of (or all) these methods? It would be simply forwarding to the underlying vectors :)

**Comment by mamcx** [comment]
I appreciate the PR!
